### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by ardier16** [intlify/vue-i18n-locale-message#139]
@kazupon, is there planning Vue 3 support for this repo?

Now it requires the `vue-template-compiler` package, which is deprecated in Vue 3, so when using `
vue-i18n-locale-message` with Vue 3 version mismatch error is thrown

**Comment by kazupon** [comment]
@ardier16 
I've just released out `v2.0.0-beta` for Vue 3 (vue-i18n-next).
Please check it! 

/cc @antfu 
You can use i18n-ally for Vue 3
(You can change from fork repo)
https://github.com/antfu/vue-i18n-locale-message-vue3
