### ISSUE TITLE
add ignorePath option to cli command

### ISSUE THREAD

**Issue by kiibo382** [intlify/vue-i18n-locale-message#149]
I think many people want to ignore files by using .ignore file. 

For example, 
add
```.ignore-i18n
**/*.vue
```
then
```bash
vue-i18n-locale message squeeze --target=./ --output=./message.json --ignorePath=./.ignore-i18n
```

I made a pull request, so I want you to check my pull request.

**Comment by kazupon** [comment]
I've just released out v1.1.0
Thanks!
