### ISSUE TITLE
📢 Notice: transfer of repository

### ISSUE THREAD

**Issue by kazupon** [intlify/vue-i18n-locale-message#70]
vue-i18n-locale-message will soon be transferred to [intlify organaization](https://github.com/intlify). After that, it will be developed and maintained on intlify.

The `vue-i18n-locale-message` that has been released on npm will be released as `@intlify/vue-i18n-locale-message` in the near future.

Intlify is a new i18n project kickoff by @kazupon. 😉

**Comment by kazupon** [comment]
I'm sorry for the confusion.

I've already migrated the repository.
As for the npm package, it is maintained with `vue-i18n-locale-message`.
Initially, I was thinking of re-publishing it as `@intlify/vue-i18n-locale-message`, but it would be too much work to re-publish and the package name would be too long, so I'm keeping it.

**Comment by mrleblanc101** [comment]
No problem.
Although, you should probably updated the README too.
